language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: NkiUD369Jj2LN3CuHZVrseTVOvIflj4e2mt0ivbrWpOabVILm5scpfTPWsDEGeYRjskkGzkZc1VmPk3tCHDlf+8wply8BkM8kw1dLZpH2H/NLiQ7bwsS3nG0/tU8Ld+Wofv2ABPHanJh8e3GCXwMREApIJsPrjf5fEO2oUbIXX4Bw0TwjXkDD9nX+tMNeo+1AdWob/QqumkUn022dKYIgrAU13j0vwNqjat4OGHgPW2lH/NunHWDGXCHCvFm/aOevYbpyPSrGTvAFQjoBzlIXVX6MmedXI/kV5eB4EEIZpc8zDxTkxcQt46pbBFRsqqwMWZj1/KsVg28t2itwgU/YdytO837V7IRcuInLNtVj9t4yEn4xft1xSOMFpZU71rCl+VQ7v20wmE1vn8LZGFCFR2XfRczrqyFbEXbcEvDshZmWwdbXX0on4SyPFBLAvWQUZ+K9lmqk9jxvwJQTSHExC4sT9/xW6tFt6RzWjxn6qdtYy7wrjXOPOVPfFPRowcSzrej5/ea0vMOi5Db9AgFbiEsEnM09yy+CoqfnEHdKIA5phj3qBX8yWHGIVInyES96IWhPpz7PzxckYVXneY7eNKVeW/Owm9rPY67iF5MvNG5oKlOH1kNeDndi1zFfeaRIIX/CZZ2sI0qUwwzZT5WmZQzJUKtpcRdvodB/QwjiL0=
  app: blog-api
  on:
    repo: mikebcbc/blog-api
